language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-1.7.9
  - rbx-2.1.1
matrix:
  allow_failures:
    - rvm: jruby-1.7.9
    - rvm: rbx-2.1.1
before_install:
  - gem update --system 2.4.8
  - gem --version
